version: "3.8"

services:
  service:
    build:
      context: ./service
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
